// Code generated by ent, DO NOT EDIT.
package admin

import (
	"time"

	"github.com/r-scheele/zero/ent/user"
)

type PasswordToken struct {
	Token     *string    `form:"token"`
	UserID    int        `form:"user_id"`
	CreatedAt *time.Time `form:"created_at"`
}

type User struct {
	Name               string                   `form:"name"`
	PhoneNumber        string                   `form:"phone_number"`
	Email              *string                  `form:"email"`
	Password           *string                  `form:"password"`
	Verified           bool                     `form:"verified"`
	VerificationCode   *string                  `form:"verification_code"`
	Admin              bool                     `form:"admin"`
	RegistrationMethod *user.RegistrationMethod `form:"registration_method"`
	ProfilePicture     *string                  `form:"profile_picture"`
	DarkMode           bool                     `form:"dark_mode"`
	Bio                *string                  `form:"bio"`
	EmailNotifications bool                     `form:"email_notifications"`
	SmsNotifications   bool                     `form:"sms_notifications"`
	IsActive           bool                     `form:"is_active"`
	LastLogin          *time.Time               `form:"last_login"`
	CreatedAt          *time.Time               `form:"created_at"`
	UpdatedAt          *time.Time               `form:"updated_at"`
}

type EntityList struct {
	Columns     []string
	Entities    []EntityValues
	Page        int
	HasNextPage bool
}

type EntityValues struct {
	ID     int
	Values []string
}

type HandlerConfig struct {
	ItemsPerPage int
	PageQueryKey string
	TimeFormat   string
}

func GetEntityTypeNames() []string {
	return []string{
		"PasswordToken",
		"User",
	}
}
