// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotesColumns holds the columns for the "notes" table.
	NotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "resources", Type: field.TypeJSON, Nullable: true},
		{Name: "ai_curriculum", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"private", "public"}, Default: "private"},
		{Name: "permission_level", Type: field.TypeEnum, Enums: []string{"read_only", "read_write", "read_write_approval"}, Default: "read_only"},
		{Name: "share_token", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "ai_processing", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_notes", Type: field.TypeInt},
	}
	// NotesTable holds the schema information for the "notes" table.
	NotesTable = &schema.Table{
		Name:       "notes",
		Columns:    NotesColumns,
		PrimaryKey: []*schema.Column{NotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notes_users_notes",
				Columns:    []*schema.Column{NotesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "note_visibility_created_at",
				Unique:  false,
				Columns: []*schema.Column{NotesColumns[6], NotesColumns[10]},
			},
			{
				Name:    "note_share_token",
				Unique:  true,
				Columns: []*schema.Column{NotesColumns[8]},
			},
		},
	}
	// NoteLikesColumns holds the columns for the "note_likes" table.
	NoteLikesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "note_likes", Type: field.TypeInt},
		{Name: "user_note_likes", Type: field.TypeInt},
	}
	// NoteLikesTable holds the schema information for the "note_likes" table.
	NoteLikesTable = &schema.Table{
		Name:       "note_likes",
		Columns:    NoteLikesColumns,
		PrimaryKey: []*schema.Column{NoteLikesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_likes_notes_likes",
				Columns:    []*schema.Column{NoteLikesColumns[2]},
				RefColumns: []*schema.Column{NotesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "note_likes_users_note_likes",
				Columns:    []*schema.Column{NoteLikesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notelike_created_at",
				Unique:  false,
				Columns: []*schema.Column{NoteLikesColumns[1]},
			},
		},
	}
	// NoteRepostsColumns holds the columns for the "note_reposts" table.
	NoteRepostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "note_reposts", Type: field.TypeInt},
		{Name: "user_note_reposts", Type: field.TypeInt},
	}
	// NoteRepostsTable holds the schema information for the "note_reposts" table.
	NoteRepostsTable = &schema.Table{
		Name:       "note_reposts",
		Columns:    NoteRepostsColumns,
		PrimaryKey: []*schema.Column{NoteRepostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_reposts_notes_reposts",
				Columns:    []*schema.Column{NoteRepostsColumns[3]},
				RefColumns: []*schema.Column{NotesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "note_reposts_users_note_reposts",
				Columns:    []*schema.Column{NoteRepostsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "noterepost_created_at",
				Unique:  false,
				Columns: []*schema.Column{NoteRepostsColumns[2]},
			},
		},
	}
	// PasswordTokensColumns holds the columns for the "password_tokens" table.
	PasswordTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// PasswordTokensTable holds the schema information for the "password_tokens" table.
	PasswordTokensTable = &schema.Table{
		Name:       "password_tokens",
		Columns:    PasswordTokensColumns,
		PrimaryKey: []*schema.Column{PasswordTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_tokens_users_user",
				Columns:    []*schema.Column{PasswordTokensColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "verification_code", Type: field.TypeString, Nullable: true},
		{Name: "admin", Type: field.TypeBool, Default: false},
		{Name: "registration_method", Type: field.TypeEnum, Enums: []string{"whatsapp", "web"}, Default: "web"},
		{Name: "profile_picture", Type: field.TypeString, Nullable: true},
		{Name: "dark_mode", Type: field.TypeBool, Default: false},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "email_notifications", Type: field.TypeBool, Default: true},
		{Name: "sms_notifications", Type: field.TypeBool, Default: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotesTable,
		NoteLikesTable,
		NoteRepostsTable,
		PasswordTokensTable,
		UsersTable,
	}
)

func init() {
	NotesTable.ForeignKeys[0].RefTable = UsersTable
	NoteLikesTable.ForeignKeys[0].RefTable = NotesTable
	NoteLikesTable.ForeignKeys[1].RefTable = UsersTable
	NoteRepostsTable.ForeignKeys[0].RefTable = NotesTable
	NoteRepostsTable.ForeignKeys[1].RefTable = UsersTable
	PasswordTokensTable.ForeignKeys[0].RefTable = UsersTable
}
