// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r-scheele/zero/ent/noterepost"
	"github.com/r-scheele/zero/ent/predicate"
)

// NoteRepostDelete is the builder for deleting a NoteRepost entity.
type NoteRepostDelete struct {
	config
	hooks    []Hook
	mutation *NoteRepostMutation
}

// Where appends a list predicates to the NoteRepostDelete builder.
func (nrd *NoteRepostDelete) Where(ps ...predicate.NoteRepost) *NoteRepostDelete {
	nrd.mutation.Where(ps...)
	return nrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nrd *NoteRepostDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nrd.sqlExec, nrd.mutation, nrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nrd *NoteRepostDelete) ExecX(ctx context.Context) int {
	n, err := nrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nrd *NoteRepostDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(noterepost.Table, sqlgraph.NewFieldSpec(noterepost.FieldID, field.TypeInt))
	if ps := nrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nrd.mutation.done = true
	return affected, err
}

// NoteRepostDeleteOne is the builder for deleting a single NoteRepost entity.
type NoteRepostDeleteOne struct {
	nrd *NoteRepostDelete
}

// Where appends a list predicates to the NoteRepostDelete builder.
func (nrdo *NoteRepostDeleteOne) Where(ps ...predicate.NoteRepost) *NoteRepostDeleteOne {
	nrdo.nrd.mutation.Where(ps...)
	return nrdo
}

// Exec executes the deletion query.
func (nrdo *NoteRepostDeleteOne) Exec(ctx context.Context) error {
	n, err := nrdo.nrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{noterepost.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nrdo *NoteRepostDeleteOne) ExecX(ctx context.Context) {
	if err := nrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
