// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r-scheele/zero/ent/note"
	"github.com/r-scheele/zero/ent/noterepost"
	"github.com/r-scheele/zero/ent/predicate"
	"github.com/r-scheele/zero/ent/user"
)

// NoteRepostQuery is the builder for querying NoteRepost entities.
type NoteRepostQuery struct {
	config
	ctx        *QueryContext
	order      []noterepost.OrderOption
	inters     []Interceptor
	predicates []predicate.NoteRepost
	withUser   *UserQuery
	withNote   *NoteQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NoteRepostQuery builder.
func (nrq *NoteRepostQuery) Where(ps ...predicate.NoteRepost) *NoteRepostQuery {
	nrq.predicates = append(nrq.predicates, ps...)
	return nrq
}

// Limit the number of records to be returned by this query.
func (nrq *NoteRepostQuery) Limit(limit int) *NoteRepostQuery {
	nrq.ctx.Limit = &limit
	return nrq
}

// Offset to start from.
func (nrq *NoteRepostQuery) Offset(offset int) *NoteRepostQuery {
	nrq.ctx.Offset = &offset
	return nrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nrq *NoteRepostQuery) Unique(unique bool) *NoteRepostQuery {
	nrq.ctx.Unique = &unique
	return nrq
}

// Order specifies how the records should be ordered.
func (nrq *NoteRepostQuery) Order(o ...noterepost.OrderOption) *NoteRepostQuery {
	nrq.order = append(nrq.order, o...)
	return nrq
}

// QueryUser chains the current query on the "user" edge.
func (nrq *NoteRepostQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: nrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(noterepost.Table, noterepost.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, noterepost.UserTable, noterepost.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(nrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNote chains the current query on the "note" edge.
func (nrq *NoteRepostQuery) QueryNote() *NoteQuery {
	query := (&NoteClient{config: nrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(noterepost.Table, noterepost.FieldID, selector),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, noterepost.NoteTable, noterepost.NoteColumn),
		)
		fromU = sqlgraph.SetNeighbors(nrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NoteRepost entity from the query.
// Returns a *NotFoundError when no NoteRepost was found.
func (nrq *NoteRepostQuery) First(ctx context.Context) (*NoteRepost, error) {
	nodes, err := nrq.Limit(1).All(setContextOp(ctx, nrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{noterepost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nrq *NoteRepostQuery) FirstX(ctx context.Context) *NoteRepost {
	node, err := nrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NoteRepost ID from the query.
// Returns a *NotFoundError when no NoteRepost ID was found.
func (nrq *NoteRepostQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nrq.Limit(1).IDs(setContextOp(ctx, nrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{noterepost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nrq *NoteRepostQuery) FirstIDX(ctx context.Context) int {
	id, err := nrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NoteRepost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NoteRepost entity is found.
// Returns a *NotFoundError when no NoteRepost entities are found.
func (nrq *NoteRepostQuery) Only(ctx context.Context) (*NoteRepost, error) {
	nodes, err := nrq.Limit(2).All(setContextOp(ctx, nrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{noterepost.Label}
	default:
		return nil, &NotSingularError{noterepost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nrq *NoteRepostQuery) OnlyX(ctx context.Context) *NoteRepost {
	node, err := nrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NoteRepost ID in the query.
// Returns a *NotSingularError when more than one NoteRepost ID is found.
// Returns a *NotFoundError when no entities are found.
func (nrq *NoteRepostQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nrq.Limit(2).IDs(setContextOp(ctx, nrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{noterepost.Label}
	default:
		err = &NotSingularError{noterepost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nrq *NoteRepostQuery) OnlyIDX(ctx context.Context) int {
	id, err := nrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NoteReposts.
func (nrq *NoteRepostQuery) All(ctx context.Context) ([]*NoteRepost, error) {
	ctx = setContextOp(ctx, nrq.ctx, ent.OpQueryAll)
	if err := nrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NoteRepost, *NoteRepostQuery]()
	return withInterceptors[[]*NoteRepost](ctx, nrq, qr, nrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nrq *NoteRepostQuery) AllX(ctx context.Context) []*NoteRepost {
	nodes, err := nrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NoteRepost IDs.
func (nrq *NoteRepostQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nrq.ctx.Unique == nil && nrq.path != nil {
		nrq.Unique(true)
	}
	ctx = setContextOp(ctx, nrq.ctx, ent.OpQueryIDs)
	if err = nrq.Select(noterepost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nrq *NoteRepostQuery) IDsX(ctx context.Context) []int {
	ids, err := nrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nrq *NoteRepostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nrq.ctx, ent.OpQueryCount)
	if err := nrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nrq, querierCount[*NoteRepostQuery](), nrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nrq *NoteRepostQuery) CountX(ctx context.Context) int {
	count, err := nrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nrq *NoteRepostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nrq.ctx, ent.OpQueryExist)
	switch _, err := nrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nrq *NoteRepostQuery) ExistX(ctx context.Context) bool {
	exist, err := nrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NoteRepostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nrq *NoteRepostQuery) Clone() *NoteRepostQuery {
	if nrq == nil {
		return nil
	}
	return &NoteRepostQuery{
		config:     nrq.config,
		ctx:        nrq.ctx.Clone(),
		order:      append([]noterepost.OrderOption{}, nrq.order...),
		inters:     append([]Interceptor{}, nrq.inters...),
		predicates: append([]predicate.NoteRepost{}, nrq.predicates...),
		withUser:   nrq.withUser.Clone(),
		withNote:   nrq.withNote.Clone(),
		// clone intermediate query.
		sql:  nrq.sql.Clone(),
		path: nrq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (nrq *NoteRepostQuery) WithUser(opts ...func(*UserQuery)) *NoteRepostQuery {
	query := (&UserClient{config: nrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nrq.withUser = query
	return nrq
}

// WithNote tells the query-builder to eager-load the nodes that are connected to
// the "note" edge. The optional arguments are used to configure the query builder of the edge.
func (nrq *NoteRepostQuery) WithNote(opts ...func(*NoteQuery)) *NoteRepostQuery {
	query := (&NoteClient{config: nrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nrq.withNote = query
	return nrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Comment string `json:"comment,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NoteRepost.Query().
//		GroupBy(noterepost.FieldComment).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nrq *NoteRepostQuery) GroupBy(field string, fields ...string) *NoteRepostGroupBy {
	nrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NoteRepostGroupBy{build: nrq}
	grbuild.flds = &nrq.ctx.Fields
	grbuild.label = noterepost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Comment string `json:"comment,omitempty"`
//	}
//
//	client.NoteRepost.Query().
//		Select(noterepost.FieldComment).
//		Scan(ctx, &v)
func (nrq *NoteRepostQuery) Select(fields ...string) *NoteRepostSelect {
	nrq.ctx.Fields = append(nrq.ctx.Fields, fields...)
	sbuild := &NoteRepostSelect{NoteRepostQuery: nrq}
	sbuild.label = noterepost.Label
	sbuild.flds, sbuild.scan = &nrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NoteRepostSelect configured with the given aggregations.
func (nrq *NoteRepostQuery) Aggregate(fns ...AggregateFunc) *NoteRepostSelect {
	return nrq.Select().Aggregate(fns...)
}

func (nrq *NoteRepostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nrq); err != nil {
				return err
			}
		}
	}
	for _, f := range nrq.ctx.Fields {
		if !noterepost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nrq.path != nil {
		prev, err := nrq.path(ctx)
		if err != nil {
			return err
		}
		nrq.sql = prev
	}
	return nil
}

func (nrq *NoteRepostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NoteRepost, error) {
	var (
		nodes       = []*NoteRepost{}
		withFKs     = nrq.withFKs
		_spec       = nrq.querySpec()
		loadedTypes = [2]bool{
			nrq.withUser != nil,
			nrq.withNote != nil,
		}
	)
	if nrq.withUser != nil || nrq.withNote != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, noterepost.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NoteRepost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NoteRepost{config: nrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nrq.withUser; query != nil {
		if err := nrq.loadUser(ctx, query, nodes, nil,
			func(n *NoteRepost, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := nrq.withNote; query != nil {
		if err := nrq.loadNote(ctx, query, nodes, nil,
			func(n *NoteRepost, e *Note) { n.Edges.Note = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nrq *NoteRepostQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*NoteRepost, init func(*NoteRepost), assign func(*NoteRepost, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*NoteRepost)
	for i := range nodes {
		if nodes[i].user_note_reposts == nil {
			continue
		}
		fk := *nodes[i].user_note_reposts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_note_reposts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (nrq *NoteRepostQuery) loadNote(ctx context.Context, query *NoteQuery, nodes []*NoteRepost, init func(*NoteRepost), assign func(*NoteRepost, *Note)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*NoteRepost)
	for i := range nodes {
		if nodes[i].note_reposts == nil {
			continue
		}
		fk := *nodes[i].note_reposts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(note.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "note_reposts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nrq *NoteRepostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nrq.querySpec()
	_spec.Node.Columns = nrq.ctx.Fields
	if len(nrq.ctx.Fields) > 0 {
		_spec.Unique = nrq.ctx.Unique != nil && *nrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nrq.driver, _spec)
}

func (nrq *NoteRepostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(noterepost.Table, noterepost.Columns, sqlgraph.NewFieldSpec(noterepost.FieldID, field.TypeInt))
	_spec.From = nrq.sql
	if unique := nrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nrq.path != nil {
		_spec.Unique = true
	}
	if fields := nrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, noterepost.FieldID)
		for i := range fields {
			if fields[i] != noterepost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nrq *NoteRepostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nrq.driver.Dialect())
	t1 := builder.Table(noterepost.Table)
	columns := nrq.ctx.Fields
	if len(columns) == 0 {
		columns = noterepost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nrq.sql != nil {
		selector = nrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nrq.ctx.Unique != nil && *nrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nrq.predicates {
		p(selector)
	}
	for _, p := range nrq.order {
		p(selector)
	}
	if offset := nrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NoteRepostGroupBy is the group-by builder for NoteRepost entities.
type NoteRepostGroupBy struct {
	selector
	build *NoteRepostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nrgb *NoteRepostGroupBy) Aggregate(fns ...AggregateFunc) *NoteRepostGroupBy {
	nrgb.fns = append(nrgb.fns, fns...)
	return nrgb
}

// Scan applies the selector query and scans the result into the given value.
func (nrgb *NoteRepostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nrgb.build.ctx, ent.OpQueryGroupBy)
	if err := nrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NoteRepostQuery, *NoteRepostGroupBy](ctx, nrgb.build, nrgb, nrgb.build.inters, v)
}

func (nrgb *NoteRepostGroupBy) sqlScan(ctx context.Context, root *NoteRepostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nrgb.fns))
	for _, fn := range nrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nrgb.flds)+len(nrgb.fns))
		for _, f := range *nrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NoteRepostSelect is the builder for selecting fields of NoteRepost entities.
type NoteRepostSelect struct {
	*NoteRepostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nrs *NoteRepostSelect) Aggregate(fns ...AggregateFunc) *NoteRepostSelect {
	nrs.fns = append(nrs.fns, fns...)
	return nrs
}

// Scan applies the selector query and scans the result into the given value.
func (nrs *NoteRepostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nrs.ctx, ent.OpQuerySelect)
	if err := nrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NoteRepostQuery, *NoteRepostSelect](ctx, nrs.NoteRepostQuery, nrs, nrs.inters, v)
}

func (nrs *NoteRepostSelect) sqlScan(ctx context.Context, root *NoteRepostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nrs.fns))
	for _, fn := range nrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
